export const QUESTION_BANNER_COPY = {
  title: "궁금한 조합, 함께 나누고 완벽한 페어링을 찾아보세요.",
  subtitle: "당신의 질문이 누군가의 완벽한 한잔이 됩니다.",
}

export const QUESTION_MOCK_SEEDS = [
  {
    id: 92001,
    authorId: 2002,
    authorName: "현우",
    title: "삼겹살에 소주 말고 어울리는 술 추천해주실분 ㅠㅠ",
    body: "매번 소주만 마셔서 다른 조합도 시도해보고 싶어요. 맥주, 하이볼 다 좋아요.",
    likeCount: 12,
    commentCount: 18,
    popularityScore: 166,
    locationLabel: "서울 강서구",
    isQna: true,
    answerCount: 18,
    answerPreview: "삼겹살엔 드라이한 하이볼이나 라거가 깔끔해요.",
    drinkType: "소주",
    categories: ["증류주"],
    detailCategories: ["소주"],
    features: ["깔끔한", "드라이한"],
    foods: ["육류"],
    searchTags: ["삼겹살", "소주", "페어링", "질문"],
    priceWon: 16000,
    abv: 16,
    minutesAgo: 10,
  },
  {
    id: 92002,
    authorId: 2019,
    authorName: "하나",
    title: "편의점 와인이랑 잘 어울리는 안주 뭐가있을까요?",
    body: "치즈 말고도 쉽게 살 수 있는 안주 조합이 궁금해요.",
    photoIds: ["question-image-1"],
    likeCount: 5,
    commentCount: 9,
    popularityScore: 120,
    locationLabel: "서울 마포구",
    isQna: true,
    answerCount: 9,
    answerPreview: "올리브, 크래커, 견과류 조합이 실패가 적어요.",
    drinkType: "와인",
    categories: ["와인"],
    detailCategories: ["화이트 와인"],
    features: ["산뜻한"],
    foods: ["치즈", "견과류"],
    searchTags: ["와인", "편의점", "안주", "질문"],
    priceWon: 22000,
    abv: 12,
    minutesAgo: 38,
  },
  {
    id: 92003,
    authorId: 2104,
    authorName: "유진",
    title: "복순도가 막걸리 마셔본 분 있나요?",
    body: "탄산감이 세다고 들었는데 실제로 어떤가요? 전이나 회랑도 잘 맞는지 궁금해요.",
    photoIds: ["question-image-2"],
    likeCount: 3,
    commentCount: 3,
    popularityScore: 88,
    locationLabel: "인천 연수구",
    isQna: true,
    answerCount: 3,
    answerPreview: "탄산감은 강한 편이고, 해물전이랑 특히 잘 어울려요.",
    drinkType: "전통주",
    categories: ["막걸리"],
    detailCategories: ["스파클링 막걸리"],
    features: ["탄산감 있는"],
    foods: ["해산물"],
    searchTags: ["복순도가", "막걸리", "탄산감", "질문"],
    priceWon: 18000,
    abv: 6,
    minutesAgo: 60,
  },
  {
    id: 92004,
    authorId: 2101,
    authorName: "태훈",
    title: "조니워커 블루라벨 선물용 괜찮을까요?",
    body: "술 좋아하는 분께 드리려고 하는데 너무 무난한 선택인지, 실제 반응이 궁금해요.",
    likeCount: 21,
    commentCount: 24,
    popularityScore: 214,
    locationLabel: "부산 해운대구",
    isQna: true,
    answerCount: 24,
    answerPreview: "선물용으로 안정적인 선택이라 대부분 반응이 좋아요.",
    drinkType: "위스키",
    categories: ["위스키"],
    detailCategories: ["블렌디드 위스키"],
    features: ["부드러운"],
    foods: ["육류"],
    searchTags: ["블루라벨", "선물", "위스키", "질문"],
    priceWon: 320000,
    abv: 40,
    minutesAgo: 180,
  },
  {
    id: 92005,
    authorId: 2003,
    authorName: "서연",
    title: "맥캘란 18년 진짜 값어치 하나요?",
    body: "위스키 입문자는 아니고 한 번쯤 좋은 술로 마셔보고 싶은데, 만족감이 궁금합니다.",
    likeCount: 11,
    commentCount: 6,
    popularityScore: 155,
    locationLabel: "대구 수성구",
    isQna: true,
    answerCount: 6,
    answerPreview: "향과 밸런스가 좋아서 특별한 날에 마시기 좋아요.",
    drinkType: "위스키",
    categories: ["위스키"],
    detailCategories: ["싱글몰트 위스키"],
    features: ["묵직한"],
    foods: ["치즈"],
    searchTags: ["맥캘란", "싱글몰트", "질문"],
    priceWon: 450000,
    abv: 43,
    minutesAgo: 300,
  },
  {
    id: 91001,
    authorId: 2116,
    title: "버번 입문 추천 부탁드려요",
    body: "메이커스 마크 다음으로 마시기 좋은 버번이 궁금해요.",
    likeCount: 42,
    commentCount: 7,
    popularityScore: 118,
    locationLabel: "일산",
    isQna: true,
    answerCount: 7,
    answerPreview: "와일드 터키 101, 버팔로 트레이스 많이 추천해요.",
    drinkType: "위스키",
    categories: ["아메리칸(버번/라이/테네시)"],
    detailCategories: ["버번"],
    features: ["무거운", "톡쏘는"],
    foods: ["치즈"],
    searchTags: ["위스키", "버번", "입문"],
    priceWon: 60000,
    abv: 45,
    minutesAgo: 11520,
  },
  {
    id: 99003,
    authorId: 9999,
    title: "혼술할 때 부담 없이 마시기 좋은 술 추천해주세요",
    body: "퇴근하고 집에서 간단하게 한잔하는 걸 좋아해요. 너무 달지 않은 걸로 추천 부탁해요.",
    photoIds: ["question_post_image_03"],
    likeCount: 23,
    commentCount: 4,
    popularityScore: 120,
    locationLabel: "서울",
    isQna: true,
    answerCount: 4,
    answerPreview: "사케 입문이면 준마이부터 천천히 가보는 것도 좋아요.",
    drinkType: "사케",
    categories: ["사케"],
    detailCategories: ["사케"],
    foods: [],
    searchTags: ["혼술", "사케", "입문"],
    priceWon: 0,
    abv: 0,
    minutesAgo: 17280,
  },
] as const
